CREATE TABLE `MoimPublic`.`user` (
  `id` BIGINT(10) NOT NULL,
  `name` CHAR(50) NOT NULL,
  `email` CHAR(50) NOT NULL,
  `profile_image` VARCHAR(200) NULL,
  `phone` CHAR(11) NOT NULL,
  `sido` CHAR(10) NOT NULL,
  `sigungu` CHAR(10) NOT NULL,
  `dong` CHAR(10) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `birthday` DATE NOT NULL,
  `detail` NVARCHAR(200) NULL,
  `isPublish` TINYINT(1) NOT NULL,
  `registerDate` DATETIME NOT NULL,
  `lastLoginDate` DATETIME NULL,
  `retireDate` DATETIME NULL,
  `level` TINYINT(1) NOT NULL,
  `role` CHAR(10) NOT NULL,

  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);
